#!/usr/bin/env python3
"""Generate library R classes for a hand-rolled (no-Gradle) Android build.

AARs do not ship R.class. Gradle generates it for the consuming app and
rewrites every library reference (Landroidx/browser/R$string; etc.) to point
at the app's merged resource table. A build that extracts classes.jar straight
out of an AAR has no such step, so the library bytecode references R types that
do not exist anywhere in the APK.

That is a NoClassDefFoundError waiting to happen the first time any code path
that touches a library resource id executes.

So: read the AAR's R.txt and emit a real R class with those exact fields.
Values are assigned from 0x7f000000 upward. They are NOT real resource ids and
are never resolved by this app - the browser-actions fallback menu, which is
the only consumer, is never instantiated (MainActivity builds a bare
CustomTabsIntent). The point is class loading, not resource lookup.

Usage: gen_lib_r.py <outdir> <libsdir>
   reads <libsdir>/closure.txt and <libsdir>/*.r.txt
"""
import os
import sys

TYPES = {'int', 'string', 'color', 'dimen', 'bool', 'integer', 'style', 'array',
         'attr', 'id', 'layout', 'drawable', 'plurals', 'fraction', 'styleable'}


def read_closure(libsdir):
    """artifact -> package, from the manifest fetch_deps.py wrote.

    The package is not the group id. androidx.lifecycle:lifecycle-runtime
    generates R into androidx.lifecycle.runtime, and androidx.concurrent:
    concurrent-futures into androidx.concurrent.futures. Rule: if the artifact
    id starts with the last segment of the group, the remainder is appended.
    """
    path = os.path.join(libsdir, 'closure.txt')
    if not os.path.exists(path):
        sys.stderr.write('no %s - run tools/fetch_deps.py first\n' % path)
        return {}
    out = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            g, a, _v = line.split(':')
            last = g.split('.')[-1]
            if a.startswith(last) and len(a) > len(last):
                a = a[len(last) + 1:]
            out[a if a else g] = g
    # rebuild as artifact -> package, keeping the original artifact key
    out = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            g, a, _v = line.split(':')
            last = g.split('.')[-1]
            pkg = g
            if a.startswith(last) and len(a) > len(last):
                pkg = g + '.' + a[len(last) + 1:].replace('-', '.')
            out[a] = pkg
    return out


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 2
    outdir, libsdir = argv[1], argv[2]
    pkgs = read_closure(libsdir)
    written = []

    for artifact, pkg in sorted(pkgs.items()):
        rtxt = os.path.join(libsdir, '%s.r.txt' % artifact)
        if not os.path.exists(rtxt):
            sys.stderr.write('skip %s (no R.txt)\n' % pkg)
            continue

        fields = {}
        with open(rtxt) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split()
                if parts[0] in ('}', '{'):
                    continue
                # "int styleable Foo = 0"      -> R$styleable.Foo
                # "int[] styleable FooBar { 0x.. }" -> R$styleable.FooBar
                if parts[0] in ('int', 'int[]') and len(parts) >= 4:
                    kind, name = parts[1], parts[2]
                    if kind in TYPES:
                        fields.setdefault(kind, []).append(name)

        dest_dir = os.path.join(outdir, *pkg.split('.'))
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, 'R.java')

        # Every library R class must extend nothing, but must be final-ish and
        # carry the nested holder classes the bytecode expects.
        with open(dest, 'w') as f:
            f.write('// GENERATED by tools/gen_lib_r.py - do not edit.\n')
            f.write('// Values are placeholders; this app never resolves them.\n')
            f.write('package %s;\n\n' % pkg)
            f.write('public final class R {\n')
            f.write('    private R() {}\n')
            n = 0x7f000000
            for kind in sorted(fields):
                # Nested class name is just the kind. The binary name
                # androidx.browser.R$color comes from nesting `color` inside
                # `R`. Writing `class R$color` here produced a class literally
                # named R$R$color, which is why the dex ended up referencing
                # R$color types it did not define.
                f.write('    public static final class %s {\n' % kind)
                f.write('        private %s() {}\n' % kind)
                for name in sorted(set(fields[kind])):
                    n += 1
                    f.write('        public static final int %s = 0x%08x;\n'
                            % (name, n))
                f.write('    }\n')
            f.write('}\n')
        written.append((pkg, dest, n))
        print('  %-34s %d field(s) -> %s' % (pkg, n - 0x7f000000, dest))

    if not written:
        sys.stderr.write('no R classes generated\n')
        return 1
    print('\ngenerated %d R class(es)' % len(written))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
